export const actionsEnum = {
  UPDATE_APPRAISAL_STEP: 'UPDATE_APPRAISAL_STEP',
  GO_TO_NEXT_STEP: 'GO_TO_NEXT_STEP',
  GO_TO_PREV_STEP: 'GO_TO_PREV_STEP',
  SAVE_VEHICLE_DATA: 'SAVE_VEHICLE_DATA',
  GO_TO_TYRES_FORM: 'GO_TO_TYRES_FORM',
  GO_TO_EQUIPMENT_FORM: 'GO_TO_EQUIPMENT_FORM',
  SAVE_TYRES_DATA: 'SAVE_TYRES_DATA'
}