export const actionsEnum = {
  SAVE_VEHICLE_DATA: 'SAVE_VEHICLE_DATA',
  SAVE_TYRES_DATA: 'SAVE_TYRES_DATA',
  SAVE_EQUIPMENT_DATA: 'SAVE_EQUIPMENT_DATA',
  SAVE_INSPECTION_DATA: 'SAVE_INSPECTION_DATA',
  SAVE_COMPONENTS_DATA: 'SAVE_COMPONENTS_DATA',
  GO_TO_VEHICLE_FORM: 'GO_TO_VEHICLE_FORM',
  GO_TO_TYRES_FORM: 'GO_TO_TYRES_FORM',
  GO_TO_EQUIPMENT_FORM: 'GO_TO_EQUIPMENT_FORM',
  GO_TO_INSPECTION_FORM: 'GO_TO_INSPECTION_FORM',
  GO_TO_COMPONENTS_FORM: 'GO_TO_COMPONENTS_FORM',
  GO_TO_DOCUMENTS_FORM: 'GO_TO_DOCUMENTS_FORM',
}